hex_file := "./target/oxide.hex"

build:
    cargo build --release

doc:
    cargo doc --release --open

objcopy: build
    cargo objcopy --release -q -- -O ihex {{hex_file}} > /dev/null

upload: objcopy
    teensy_loader_cli --mcu=imxrt1062 -vw {{hex_file}}

usb:
    sleep 1
    screen /dev/tty.usbmodem62135501
    reset