name: Build Devlog
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-linkcheck
        run: |
          curl -s https://api.github.com/repos/Michael-F-Bryan/mdbook-linkcheck/releases/latest \
          | grep browser_download_url \
          | grep $(rustc -Vv | grep host | cut -d' ' -f2) \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -

      - run: mdbook build
        working-directory: devlog

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./devlog/book/html
          publish_branch: devlog-rendered
