name: Build Devlog
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-linkcheck
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

      - run: mdbook build
        working-directory: devlog

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./devlog/book/html
          publish_branch: devlog-rendered
          cname: rocketry.dusterthefirst.com
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
